select count(*) from call_center_tcpds;
/*ydb.pushdown('->')*/select count(*) from call_center_tcpydb                /*('<-')pushdown.ydb*/;
select count(*) from catalog_page_tcpds;
/*ydb.pushdown('->')*/select count(*) from catalog_page_tcpydb               /*('<-')pushdown.ydb*/;
select count(*) from catalog_returns_tcpds;
/*ydb.pushdown('->')*/select count(*) from catalog_returns_tcpydb            /*('<-')pushdown.ydb*/;
select count(*) from catalog_sales_tcpds;
/*ydb.pushdown('->')*/select count(*) from catalog_sales_tcpydb              /*('<-')pushdown.ydb*/;
select count(*) from customer_address_tcpds;
/*ydb.pushdown('->')*/select count(*) from customer_address_tcpydb           /*('<-')pushdown.ydb*/;
select count(*) from customer_demographics_tcpds;
/*ydb.pushdown('->')*/select count(*) from customer_demographics_tcpydb      /*('<-')pushdown.ydb*/;
select count(*) from customer_tcpds;
/*ydb.pushdown('->')*/select count(*) from customer_tcpydb                   /*('<-')pushdown.ydb*/;
select count(*) from date_dim_tcpds;
/*ydb.pushdown('->')*/select count(*) from date_dim_tcpydb                   /*('<-')pushdown.ydb*/;
select count(*) from household_demographics_tcpds;
/*ydb.pushdown('->')*/select count(*) from household_demographics_tcpydb     /*('<-')pushdown.ydb*/;
select count(*) from income_band_tcpds;
/*ydb.pushdown('->')*/select count(*) from income_band_tcpydb                /*('<-')pushdown.ydb*/;
select count(*) from inventory_tcpds;
/*ydb.pushdown('->')*/select count(*) from inventory_tcpydb                  /*('<-')pushdown.ydb*/;
select count(*) from item_tcpds;
/*ydb.pushdown('->')*/select count(*) from item_tcpydb                       /*('<-')pushdown.ydb*/;
select count(*) from promotion_tcpds;
/*ydb.pushdown('->')*/select count(*) from promotion_tcpydb                  /*('<-')pushdown.ydb*/;
select count(*) from reason_tcpds;
/*ydb.pushdown('->')*/select count(*) from reason_tcpydb                     /*('<-')pushdown.ydb*/;
select count(*) from ship_mode_tcpds;
/*ydb.pushdown('->')*/select count(*) from ship_mode_tcpydb                  /*('<-')pushdown.ydb*/;
select count(*) from store_returns_tcpds;
/*ydb.pushdown('->')*/select count(*) from store_returns_tcpydb              /*('<-')pushdown.ydb*/;
select count(*) from store_sales_tcpds;
/*ydb.pushdown('->')*/select count(*) from store_sales_tcpydb                /*('<-')pushdown.ydb*/;
select count(*) from store_tcpds;
/*ydb.pushdown('->')*/select count(*) from store_tcpydb                      /*('<-')pushdown.ydb*/;
select count(*) from time_dim_tcpds;
/*ydb.pushdown('->')*/select count(*) from time_dim_tcpydb                   /*('<-')pushdown.ydb*/;
select count(*) from warehouse_tcpds;
/*ydb.pushdown('->')*/select count(*) from warehouse_tcpydb                  /*('<-')pushdown.ydb*/;
select count(*) from web_page_tcpds;
/*ydb.pushdown('->')*/select count(*) from web_page_tcpydb                   /*('<-')pushdown.ydb*/;
select count(*) from web_returns_tcpds;
/*ydb.pushdown('->')*/select count(*) from web_returns_tcpydb                /*('<-')pushdown.ydb*/;
select count(*) from web_sales_tcpds;
/*ydb.pushdown('->')*/select count(*) from web_sales_tcpydb                  /*('<-')pushdown.ydb*/;
select count(*) from web_site_tcpds;
/*ydb.pushdown('->')*/select count(*) from web_site_tcpydb                   /*('<-')pushdown.ydb*/;
